# Generated by Django 2.1.5 on 2019-02-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myStockApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=32, unique=True)),
                ('exchange', models.CharField(max_length=32)),
                ('chairman', models.CharField(max_length=32)),
                ('manager', models.CharField(max_length=32)),
                ('secretary', models.CharField(max_length=32)),
                ('reg_capital', models.CharField(max_length=32)),
                ('setup_date', models.CharField(max_length=32)),
                ('province', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('introduction', models.TextField(null=True)),
                ('website', models.CharField(max_length=32, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('employees', models.CharField(max_length=32, null=True)),
                ('main_business', models.TextField(null=True)),
                ('business_scope', models.TextField(null=True)),
            ],
        ),
    ]
