# Generated by Django 2.1.5 on 2019-03-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myStockApp', '0002_stockdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStockDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserCollectionDetails_username', models.CharField(max_length=32)),
                ('UserCollectionDetails_name', models.CharField(max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='list_date',
            field=models.CharField(max_length=32),
        ),
    ]
