# Generated by Django 2.1.5 on 2019-03-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myStockApp', '0003_auto_20190302_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=32)),
                ('datetime', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('channels', models.CharField(max_length=32)),
                ('content', models.TextField()),
            ],
        ),
    ]
