# Generated by Django 2.1.5 on 2019-03-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myStockApp', '0004_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
