# Generated by Django 2.1.5 on 2019-03-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myStockApp', '0005_auto_20190316_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='datetime',
            field=models.CharField(max_length=32),
        ),
    ]
